### ISSUE TITLE
[Error: Code: -2004 Msg: Can't initialize DBCAPI]

### ISSUE THREAD

**Issue by andre-pentaxial** [sqlanywhere/node-sqlanywhere#12]
I i'm getting this error:
[Error: Code: -2004 Msg: Can't initialize DBCAPI]

Could you help me solve this?

**Comment by gperrow-SAP** [comment]
We'll need a little more information. What platform are you running on? What version of the SQL Anywhere client do you have installed?

**Comment by gperrow-SAP** [comment]
The documentation for PHP support is here: http://dcx.sap.com/index.html#sa160/en/dbprogramming/pg-php.html*d5e36209

If you have questions about PHP, you can post them at http://sqlanywhere-forum.sap.com/
