### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by finedays** [sqlanywhere/node-sqlanywhere#16]
Hi, I am having the following error:

> Error: Code: -869 Msg: Database server cannot convert data from/to character set 'UTF-8'

Where I can set the desired encoding for the connection?

Thanks!

**Comment by gperrow-SAP** [comment]
You can use the CHARSET connection parameter to set the character set to be used for a connection. This parameter is documented [here](http://dcx.sap.com/index.html#sqla170/en/html/812f075d6ce21014a3518b253f362c3c.html*loio812f075d6ce21014a3518b253f362c3c) (this is documentation for SQLA v17, though the parameter is the same in other versions).

This is not specific to the node.js driver, so if you still have trouble, you may want to post a question at http://sqlanywhere-forum.sap.com/.

**Comment by finedays** [comment]
Hi, 

I asked the question there, but no one seems to have a solution.. 
http://sqlanywhere-forum.sap.com/questions/27543/how-to-set-charset-using-nodejs-driver-with-osx
If you can help me a little bit more I will be very very happy :)

**Comment by gperrow-SAP** [comment]
The question has only been open a few hours. Most of the SQL Anywhere team is in Waterloo, Ontario, Canada, where almost nobody has seen it yet (it was asked at 4am local time). It's also Canada Day today so most Canadians are not working.

**Comment by finedays** [comment]
Ok. Finally I fixed it by replacing the 'UTF-8' to 'UTF8' into sqlanywhere.cpp and sqlanywhere_v0_10.cpp files and rebuilt the driver with node-gyp.

**Comment by hagen** [comment]
Should this be changed in the cpp files then? What's the actual issue here?
I'm getting the same error. @finedays I attempted to rebuild on Win also, but it's complaining about missing csproj.
@gperrow-SAP the connection options don't support the CharSet prop - where can this be configured. It looks like the string `UTF-8` is hard-coded in the cpp file?
