### ISSUE TITLE
Resource governor for 'prepared statements' exceeded with v1.0.11

### ISSUE THREAD

**Issue by alevinru** [sqlanywhere/node-sqlanywhere#18]
I do not use prepared statements. Just conn.exec(sql, params, callback) then conn.commit(callback).

Everything's fine with v1.0.10

**Comment by gperrow-SAP** [comment]
This is fixed with version 1.0.12. I'm having trouble uploading the new module to npm but it will hopefully be there very soon. Thanks for reporting the problem.

**Comment by alevinru** [comment]
Everything's ok now, thank you.
