### ISSUE TITLE
Build issue during sqlanywhere package installation

### ISSUE THREAD

**Issue by morpheusdev** [sqlanywhere/node-sqlanywhere#24]
Getting the following errors while installing sqlanywhere package for ubuntu 16.04 LTS

Looking for binaries...
Trying to build binaries
Error when executing node-gyp configure
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "sqlanywhere"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 255

npm ERR! sqlanywhere@1.0.17 install: `node build.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the sqlanywhere@1.0.17 install script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlanywhere package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js

**Comment by gperrow-SAP** [comment]
This problem should be fixed with version 1.0.18.
