### ISSUE TITLE
How to check if the connection is alive?

### ISSUE THREAD

**Issue by alevinru** [sqlanywhere/node-sqlanywhere#9]
We have an app with a pool of db connections. Pooling mechanism would like to check if the connection is still alive every time before acquires it. How can we implement this check?

**Comment by gperrow-SAP** [comment]
There isn't a specific way to do this, though you could execute a simple "select 1" fetch on the connection, checking for error code -308 "Connection was terminated".

**Comment by noelhibbard** [comment]
I know this is an old question but there does seem to be an undocumented way to check, connection.connected() will return a bool.
